package starmap

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestNumberUnmarshal(t *testing.T) {
	// The Starmap API delivers some numbers quoted and others bare; both must
	// decode to the same value.
	cases := []struct {
		in   string
		want Number
	}{
		{`12.79`, 12.79},
		{`"12.79000000"`, 12.79},
		{`"4"`, 4},
		{`0`, 0},
		{`null`, 0},
		{`""`, 0},
		{`-1`, -1},
	}
	for _, c := range cases {
		var n Number
		if err := json.Unmarshal([]byte(c.in), &n); err != nil {
			t.Fatalf("Unmarshal(%s): %v", c.in, err)
		}
		if n != c.want {
			t.Errorf("Unmarshal(%s) = %v, want %v", c.in, n, c.want)
		}
	}
}

func TestNumberUnmarshalRejectsNonNumericString(t *testing.T) {
	var n Number
	if err := json.Unmarshal([]byte(`"not a number"`), &n); err == nil {
		t.Fatal("expected an error for a non-numeric string, got nil")
	}
}

// TestLargeNumbersKeepDecimalNotation guards a regression: supplying a custom
// MarshalJSON using strconv 'g' formatting rewrote large values into exponent
// notation (3458865.2579 became 3.4588652579e+06), which silently changed a
// megabyte of wiki content. Number must marshal via encoding/json's own
// ECMAScript-compatible float encoder.
func TestLargeNumbersKeepDecimalNotation(t *testing.T) {
	cases := []struct {
		in   Number
		want string
	}{
		{3458865.2579, "3458865.2579"},
		{1235564.1649749, "1235564.1649749"},
		{3132000, "3132000"},
		{99999999.99999999, "99999999.99999999"},
		{12.79, "12.79"},
		{0, "0"},
		{-1, "-1"},
	}
	for _, c := range cases {
		b, err := json.Marshal(c.in)
		if err != nil {
			t.Fatalf("Marshal(%v): %v", c.in, err)
		}
		if got := string(b); got != c.want {
			t.Errorf("Marshal(%v) = %s, want %s", float64(c.in), got, c.want)
		}
	}
}

// TestEncodeShapeMatchesWikiCanonicalForm checks the two properties that let
// the generated bytes be compared against the wiki page directly: tab indenting
// and &-style escaping of HTML-significant characters.
func TestEncodeShapeMatchesWikiCanonicalForm(t *testing.T) {
	desc := "Rough &amp; Ready <b> 'quoted'"
	doc := &Document{
		Systems: []System{{
			ID:          1,
			Code:        "TEST",
			Description: desc,
			Name:        "Test",
			Affiliation: []Affiliation{},
		}},
		Objects: []Object{},
	}
	out, err := Encode(doc)
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)

	if !strings.Contains(s, "\\u0026") {
		t.Errorf("expected & escaped as \\\\u0026 to match MediaWiki; got %s", s)
	}
	if !strings.Contains(s, "\\u003c") || !strings.Contains(s, "\\u003e") {
		t.Errorf("expected < and > escaped to match MediaWiki; got %s", s)
	}
	if strings.Contains(s, "\\u0027") {
		t.Errorf("apostrophes must NOT be escaped; MediaWiki leaves them literal; got %s", s)
	}
	if !strings.Contains(s, "\n\t\"systems\": [") {
		t.Error("expected tab indentation")
	}
	if !strings.HasSuffix(s, "\n") {
		t.Error("expected a trailing newline for a well-formed file on disk")
	}
}

// TestEmptyAffiliationSerialisesAsArray keeps an absent affiliation list from
// becoming null, which would differ from the existing page.
func TestEmptyAffiliationSerialisesAsArray(t *testing.T) {
	b, err := json.Marshal(System{Affiliation: orEmpty(nil)})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), `"affiliation":[]`) {
		t.Errorf("expected an empty array, got %s", b)
	}
}

// TestObjectCarriesDistance pins the field the mirror used to drop, which was
// being decoded into nothing.
//
// It is the ordering signal upstream ships for a belt, which is otherwise the one
// body with no orbital slot to fall back on: 68 of the 69 carry a distance — only
// Kallis V Accretion Disk does not — while just two, `Ellis XI` and `Odin I`, end
// in a Roman numeral the rail can read. Odin's rail turns on that second one:
// `Odin I` is The Coil, which ties Gainey at 1.1 and takes the earlier slot
// because it has a numeral and Gainey has none.
//
// The 62 in cmd/systemmap/README.md counts something else and is right there:
// how many belts `distance` PLACES, which is the 69 less the seven the overlay's
// surviving `after` entries position instead.
//
// It is a POINTER because absence is meaningful and distinct from zero: thirteen
// objects genuinely have none, while every star sits at a real 0 from itself. A
// bare Number would decode both to 0 and make "upstream has no figure" and
// "upstream says it is at the centre" the same claim.
func TestObjectCarriesDistance(t *testing.T) {
	cases := []struct {
		in   string
		want *Number
	}{
		{`{"distance": 30.4413}`, ptr(Number(30.4413))},   // Neptune, AU from the Sun
		{`{"distance": 0.000234}`, ptr(Number(0.000234))}, // Rings of Uranus, AU from Uranus
		{`{"distance": "2.15"}`, ptr(Number(2.15))},       // the API quotes some numbers
		{`{"distance": 0}`, ptr(Number(0))},               // a star, or Min's rogue planet
		{`{"distance": null}`, nil},                       // Kallis' accretion disk
		{`{}`, nil},
	}
	for _, c := range cases {
		var obj Object
		if err := json.Unmarshal([]byte(c.in), &obj); err != nil {
			t.Fatalf("Unmarshal(%s): %v", c.in, err)
		}
		switch {
		case c.want == nil && obj.Distance != nil:
			t.Errorf("Unmarshal(%s).Distance = %v, want nil", c.in, *obj.Distance)
		case c.want != nil && obj.Distance == nil:
			t.Errorf("Unmarshal(%s).Distance = nil, want %v", c.in, *c.want)
		case c.want != nil && *obj.Distance != *c.want:
			t.Errorf("Unmarshal(%s).Distance = %v, want %v", c.in, *obj.Distance, *c.want)
		}
	}
}

// TestDistanceSurvivesARoundTrip checks the wire format, since these bytes are
// compared against the wiki page directly: an absent distance must write as null
// like every other optional number here, and a present one must keep decimal
// notation rather than slipping into exponent form.
func TestDistanceSurvivesARoundTrip(t *testing.T) {
	doc := &Document{Objects: []Object{
		{ID: 1, Code: "A", Distance: ptr(Number(0.000234)), Affiliation: []Affiliation{}},
		{ID: 2, Code: "B", Affiliation: []Affiliation{}},
	}}
	out, err := Encode(doc)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), `"distance": 0.000234`) {
		t.Errorf("expected decimal notation for a small distance, got:\n%s", out)
	}
	if !strings.Contains(string(out), `"distance": null`) {
		t.Errorf("expected an absent distance to write as null, got:\n%s", out)
	}

	back, err := Decode(out)
	if err != nil {
		t.Fatal(err)
	}
	if back.Objects[0].Distance == nil || *back.Objects[0].Distance != 0.000234 {
		t.Errorf("distance did not survive the round trip: %v", back.Objects[0].Distance)
	}
	if back.Objects[1].Distance != nil {
		t.Errorf("null decoded as %v, want nil", *back.Objects[1].Distance)
	}
}

func ptr[T any](v T) *T { return &v }

func TestCompareDetectsFieldChange(t *testing.T) {
	mk := func(danger Number) *Document {
		return &Document{Systems: []System{{ID: 1, Code: "A", Name: "A", AggregatedDanger: danger}}}
	}
	lines := Compare(mk(4.53), mk(0))
	joined := strings.Join(lines, "\n")
	if !strings.Contains(joined, "aggregated_danger") {
		t.Errorf("expected the changed field to be named, got:\n%s", joined)
	}
	if !strings.Contains(joined, "1 changed") {
		t.Errorf("expected one changed record, got:\n%s", joined)
	}
}

func TestCompareDetectsAddedAndRemoved(t *testing.T) {
	oldDoc := &Document{Systems: []System{{ID: 1, Code: "KEEP"}, {ID: 2, Code: "GONE"}}}
	newDoc := &Document{Systems: []System{{ID: 1, Code: "KEEP"}, {ID: 3, Code: "NEW"}}}
	joined := strings.Join(Compare(oldDoc, newDoc), "\n")
	if !strings.Contains(joined, "+1 added") || !strings.Contains(joined, "-1 removed") {
		t.Errorf("expected one added and one removed, got:\n%s", joined)
	}
}
